defaultSemverRangePrefix: ""

enableGlobalCache: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0007
    level: discard
  - code: YN0013
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.3.cjs
