export enum ComponentName {
  HEADER_ARTICLE = "HEADER_ARTICLE",
  LEGAL_TEXT = "LEGAL_TEXT",
  ROTATING_CUBE = "ROTATING_CUBE",
  SECTION_IMAGE = "SECTION_IMAGE",
  SECTION_TIMELINE = "SECTION_TIMELINE",
  THUMBS_GALLERY = "THUMBS_GALLERY",
}
