export enum ComponentName {
  ARTICLE_SECTION = "ARTICLE_SECTION",
  FRAME_SECTION = "FRAME_SECTION",
  IMAGE_SECTION = "IMAGE_SECTION",
  LEGAL_SECTION = "LEGAL_SECTION",
  ROTATING_CUBE = "ROTATING_CUBE",
  TIMELINE_SECTION = "TIMELINE_SECTION",
}
