export enum RoutePath {
  ARRHYTHIMIA_CLASSIFICATION = "/thoughts/arrhythmia-classification/",
  AUBERGE_DE_CERCOUX = "/ventures/auberge-de-cercoux/",
  BOOK_SUGGESTIONS = "/suggestions/books/",
  CALASTER = "/ventures/calaster/",
  DILLYGENCE = "/ventures/dillygence/",
  ENHANCER_SUGGESTIONS = "/suggestions/enhancers/",
  FUJITSU = "/ventures/fujitsu/",
  FUTURE_OF_STORYTELLING = "/thoughts/future-of-storytelling/",
  LANDING_PAGE = "/",
  LEARNING_DIFFERENCES = "/thoughts/learning-differences/",
  MENTIONS = "/mentions/",
  MISSIONS = "/missions/",
  MODELS_HUMAN_COGNITION = "/thoughts/models-human-cognition/",
  NEWSLETTER_SUGGESTIONS = "/suggestions/newsletters/",
  PODCAST_SUGGESTIONS = "/suggestions/podcasts/",
  POLYGON = "/ventures/polygon/",
  PRIVACY_POLICY = "/legal/privacy-policy/",
  SLEEP_STAGE_CLASSIFICATION = "/thoughts/sleep-stage-classification/",
  SUGGESTIONS = "/suggestions/",
  SYSNAV = "/ventures/sysnav/",
  TERMS_OF_USE = "/legal/terms-of-use/",
  THOUGHTS = "/thoughts/",
  TOMATO_CLUSTERING = "/thoughts/tomato-clustering/",
  TOPOLOGICAL_DATA_ANALYSIS = "/thoughts/topological-data-analysis/",
  TOOLKIT_SUGGESTIONS = "/suggestions/toolkits/",
  VENTURES = "/ventures/",
}
