export enum RoutePath {
  ARRHYTHIMIA_CLASSIFICATION = "/think/arrhythmia-classification/",
  AUBERGE_DE_CERCOUX = "/hustle/auberge-de-cercoux/",
  CALASTER = "/hustle/calaster/",
  DILLYGENCE = "/hustle/dillygence/",
  FUJITSU = "/hustle/fujitsu/",
  HUSTLE = "/hustle/",
  LANDING_PAGE = "/",
  POLYGON = "/hustle/polygon/",
  PRIVACY_POLICY = "/legal/privacy-policy/",
  SYSNAV = "/hustle/sysnav/",
  TERMS_OF_USE = "/legal/terms-of-use/",
  THINK = "/think/",
  TOMATO_CLUSTERING = "/think/tomato-clustering/",
  TOPOLOGICAL_DATA_ANALYSIS = "/think/topological-data-analysis/",
}
