export enum RoutePath {
  ARRHYTHIMIA_CLASSIFICATION = "/think/arrhythmia-classification/",
  AUBERGE_DE_CERCOUX = "/hustle/auberge-de-cercoux/",
  CALASTER = "/hustle/calaster/",
  DILLYGENCE = "/hustle/dillygence/",
  FUJITSU = "/hustle/fujitsu/",
  FUTURE_OF_STORYTELLING = "/think/future-of-storytelling/",
  HUSTLE = "/hustle/",
  LANDING_PAGE = "/",
  LEARNING_DIFFERENCES = "/think/learning-differences/",
  MODELS_HUMAN_COGNITION = "/think/models-human-cognition/",
  POLYGON = "/hustle/polygon/",
  PRIVACY_POLICY = "/legal/privacy-policy/",
  SLEEP_STAGE_CLASSIFICATION = "/think/sleep-stage-classification/",
  SYSNAV = "/hustle/sysnav/",
  TERMS_OF_USE = "/legal/terms-of-use/",
  THINK = "/think/",
  TOMATO_CLUSTERING = "/think/tomato-clustering/",
  TOPOLOGICAL_DATA_ANALYSIS = "/think/topological-data-analysis/",
}
