export enum ColorName {
  BACKGROUND = "background",
  SURFACE = "surface",
  PRIMARY = "primary",
  SECONDARY = "secondary",
  ERROR = "error",
  INFO = "info",
  SUCCESS = "success",
  WARNING = "warning",
  FOAM = "foam",
  LEMON = "lemon",
  SLATE_GRAY = "slate-gray",
}

export enum IconName {
  AT = "AT",
  BOOKSHELF = "BOOKSHELF",
  BRAIN = "BRAIN",
  CAMERA = "CAMERA",
  COOKIE_CHECK = "COOKIE_CHECK",
  FACEBOOK = "FACEBOOK",
  FACTORY = "FACTORY",
  FIRE = "FIRE",
  FOOD_CROISSANT = "FOOD_CROISSANT",
  GITHUB = "GITHUB",
  HEART_PULSE = "HEART_PULSE",
  INSTAGRAM = "INSTAGRAM",
  LINKEDIN = "LINKEDIN",
  NOTEBOOK = "NOTEBOOK",
  SCHOOL = "SCHOOL",
  SILVERWARE_FORK_KNIFE = "SILVERWARE_FORK_KNIFE",
  TWITTER = "TWITTER",
  WEB = "WEB",
  YOUTUBE = "YOUTUBE",
}
