import ANIMATED_AVATAR_CONTENT from "./ANIMATED_AVATAR.json";
import COOKIE_BANNER_CONTENT from "./COOKIE_BANNER.json";
import ERROR_PAGE_CONTENT from "./ERROR_PAGE.json";
import GLOBAL_FOOTER_CONTENT from "./GLOBAL_FOOTER.json";

export const LAYOUT_CONTENT = {
  animatedAvatar: ANIMATED_AVATAR_CONTENT,
  cookieBanner: COOKIE_BANNER_CONTENT,
  errorPage: ERROR_PAGE_CONTENT,
  globalFooter: GLOBAL_FOOTER_CONTENT,
};
