import {
  ARRHYTHMIA_CLASSIFICATION,
  AUBERGE_PAGE_CONTENT,
  CALASTER_PAGE_CONTENT,
  DILLYGENCE_PAGE_CONTENT,
  FUJITSU_PAGE_CONTENT,
  HUSTLE_PAGE_CONTENT,
  LANDING_PAGE_CONTENT,
  POLYGON_PAGE_CONTENT,
  PRIVACY_POLICY_CONTENT,
  SYSNAV_PAGE_CONTENT,
  TERMS_OF_USE_CONTENT,
  THINK_PAGE_CONTENT,
  TOMATO_CLUSTERING_BLOG,
  TOPOLOGICAL_DATA_ANALYSIS_BLOG,
} from "@/content";
import { RoutePath } from "@/types";

export const ROUTES_CONTENT = {
  [RoutePath.ARRHYTHIMIA_CLASSIFICATION]: ARRHYTHMIA_CLASSIFICATION,
  [RoutePath.AUBERGE_DE_CERCOUX]: AUBERGE_PAGE_CONTENT,
  [RoutePath.CALASTER]: CALASTER_PAGE_CONTENT,
  [RoutePath.DILLYGENCE]: DILLYGENCE_PAGE_CONTENT,
  [RoutePath.FUJITSU]: FUJITSU_PAGE_CONTENT,
  [RoutePath.HUSTLE]: HUSTLE_PAGE_CONTENT,
  [RoutePath.LANDING_PAGE]: LANDING_PAGE_CONTENT,
  [RoutePath.POLYGON]: POLYGON_PAGE_CONTENT,
  [RoutePath.PRIVACY_POLICY]: PRIVACY_POLICY_CONTENT,
  [RoutePath.SYSNAV]: SYSNAV_PAGE_CONTENT,
  [RoutePath.TERMS_OF_USE]: TERMS_OF_USE_CONTENT,
  [RoutePath.THINK]: THINK_PAGE_CONTENT,
  [RoutePath.TOMATO_CLUSTERING]: TOMATO_CLUSTERING_BLOG,
  [RoutePath.TOPOLOGICAL_DATA_ANALYSIS]: TOPOLOGICAL_DATA_ANALYSIS_BLOG,
};
