import {
  mdiAt,
  mdiBookshelf,
  mdiBrain,
  mdiCamera,
  mdiCompassOutline,
  mdiCookieCheck,
  mdiDna,
  mdiEmailNewsletter,
  mdiFacebook,
  mdiFactory,
  mdiFire,
  mdiFoodCroissant,
  mdiGithub,
  mdiHeartPulse,
  mdiInstagram,
  mdiLinkedin,
  mdiNotebook,
  mdiPodcast,
  mdiSchool,
  mdiSilverwareForkKnife,
  mdiTools,
  mdiTwitter,
  mdiWeb,
  mdiYoutube,
} from "@mdi/js";

import { IconName } from "@/types";

export const ICONS: Record<IconName, string> = {
  [IconName.AT]: mdiAt,
  [IconName.BOOKSHELF]: mdiBookshelf,
  [IconName.BRAIN]: mdiBrain,
  [IconName.CAMERA]: mdiCamera,
  [IconName.COMPASS_OUTLINE]: mdiCompassOutline,
  [IconName.COOKIE_CHECK]: mdiCookieCheck,
  [IconName.DNA]: mdiDna,
  [IconName.EMAIL_NEWSLETTER]: mdiEmailNewsletter,
  [IconName.FACEBOOK]: mdiFacebook,
  [IconName.FACTORY]: mdiFactory,
  [IconName.FIRE]: mdiFire,
  [IconName.FOOD_CROISSANT]: mdiFoodCroissant,
  [IconName.GITHUB]: mdiGithub,
  [IconName.HEART_PULSE]: mdiHeartPulse,
  [IconName.INSTAGRAM]: mdiInstagram,
  [IconName.LINKEDIN]: mdiLinkedin,
  [IconName.NOTEBOOK]: mdiNotebook,
  [IconName.PODCAST]: mdiPodcast,
  [IconName.SCHOOL]: mdiSchool,
  [IconName.SILVERWARE_FORK_KNIFE]: mdiSilverwareForkKnife,
  [IconName.TOOLS]: mdiTools,
  [IconName.TWITTER]: mdiTwitter,
  [IconName.WEB]: mdiWeb,
  [IconName.YOUTUBE]: mdiYoutube,
};
