name: helix

on: [pull_request, merge_group]

env:
  NODE_VERSION: "18.16"

jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-helix-${{ hashFiles('yarn.lock') }}

      - name: Cache Cypress
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.OS }}-cypress-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: make install

      - name: Run Prettier
        run: yarn prettier

      - name: Run ESLint
        run: yarn eslint

      - name: Run Stylelint
        run: yarn stylelint

      - name: Bundle Application
        run: make build

      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          command: yarn cypress
          install: false
          start: make serve
          wait-on: "http://localhost:3000/"
          wait-on-timeout: 60
